name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync to Hugging Face Hub
        uses: huggingface/sync-to-hub@v0.5
        with:
          repo_id: "taehoon222/emotion-chatbot-app"
          repo_type: "space"
          token: ${{ secrets.HF_TOKEN }}